spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
      tablePrefix: batch.BATCH_
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql-batch.sql